Update .spi.yml
Documentation building and hosting on SPI is failing because the config file references non-existing targets:

```
Build complete! (0.12s)
error: no target named 'GliderSwiftLog'

compatible targets: 'Glider'"
```